server.port: 5004

##H2 database configuration
spring:
  h2:
    console:
      enabled: true
  datasource:
   url: jdbc:h2:mem:searchDb
   driverClassName: org.h2.Driver
   username: sa
   password: password
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect

